Repository charmbracelet/soft-serve, pull requests merged in 2023-05, with the labels that each got.

#269 feat: log time format
  cmd/soft/root.go
  server/config/config.go
  server/config/file.go
Labels: enhancement

#272 fix: increase clone timeout, fix some lint issues
  git/repo.go
  server/backend/sqlite/sqlite.go
Labels: enhancement

#282 fix: improve dockerfile caching
  Dockerfile
Labels: enhancement

#284 fix: set CI=1 in Dockerfile as a workaround
  Dockerfile
Labels: bug, docker

#309 fix: ignore case README filenames
  server/backend/utils.go
Labels: documentation

#305 test: smoke tests with testscript
  .editorconfig
  .gitattributes
  .github/workflows/build.yml
  go.mod
  go.sum
  server/backend/sqlite/user.go
  server/cmd/repo.go
  server/hooks/hooks.go
  server/jobs.go
  server/server.go
  server/test/test.go
  server/utils/utils.go
  server/utils/utils_test.go
  testscript/script_test.go
  testscript/testdata/mirror.txtar
  testscript/testdata/repo-collab.txtar
  testscript/testdata/repo-create.txtar
  testscript/testdata/repo-import.txt
  testscript/testdata/set-username.txtar
  testscript/testdata/settings.txtar
  testscript/testdata/user_management.txtar
Labels: enhancement

#312 test: repo tree tests
  git/repo.go
  testscript/testdata/repo-tree.txtar
Labels: enhancement

#315 fix: metric cardinality et al
  server/cmd/cmd.go
  server/ssh/session.go
  server/ssh/ssh.go
Labels: enhancement
